language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
sudo: required
env:
- GEOSERVER_VERSION=latest
- GEOSERVER_VERSION=maintenance
services:
- docker
before_install:
- docker pull oscarfonts/geoserver:${GEOSERVER_VERSION}
- docker run -d -p 8080:8080 --name=geoserver oscarfonts/geoserver:${GEOSERVER_VERSION}
script:
- make test
notifications:
  email:
    recipients:
      - victor.gonzalez@geomati.co
    on_success: always

